/**
 * Generated by data-pipeline/build_catalog.py - do not edit by hand.
 *
 * The catalog itself (`data-pipeline/out/universities.json`) is a gitignored
 * build artifact, so these counts are committed instead: the hero and the
 * static-demo notice render before any fetch and still have to be honest.
 * Anywhere the catalog is already loaded, count it rather than importing this.
 */

export const CATALOG_SIZE = 358;
export const RURAL_COUNT = 28;
export const WITH_DETAILS_COUNT = 276;
