/**
 * Majors offered by at least three schools in the catalog, derived from
 * data-pipeline/out/universities.json. Deriving rather than hand-listing means
 * no option can return zero results by construction.
 */
export const MAJORS = [
  "Accounting",
  "Actuarial Science",
  "Aerospace",
  "Agriculture",
  "Animation",
  "Architecture",
  "Art",
  "Art History",
  "Astronomy",
  "Aviation",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Business",
  "Chemistry",
  "Communication",
  "Communications",
  "Composition",
  "Computer Science",
  "Conducting",
  "Creative Writing",
  "Criminal Justice",
  "Criminology",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dentistry",
  "Design",
  "Drama",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Engineering",
  "English",
  "Environmental Science",
  "Environmental Studies",
  "Fashion",
  "Film",
  "Finance",
  "Fine Arts",
  "Game Design",
  "Geology",
  "Government",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality",
  "Illustration",
  "Industrial Design",
  "International Relations",
  "International Studies",
  "Jazz Studies",
  "Journalism",
  "Kinesiology",
  "Law",
  "Literature",
  "Management",
  "Marine Science",
  "Marketing",
  "Materials Science",
  "Math",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Mining",
  "Music",
  "Music Business",
  "Neuroscience",
  "Nursing",
  "Oceanography",
  "Performance",
  "Petroleum Engineering",
  "Pharmacy",
  "Philosophy",
  "Photography",
  "Physics",
  "Political Science",
  "Politics",
  "Pre-Med",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Robotics",
  "Sciences",
  "Social Work",
  "Songwriting",
  "Supply Chain",
  "Theatre",
  "Veterinary Science"
] as const;
